name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
                uses: actions/checkout@v2

            - name: Deploy
                run: |
                    git subtree split --prefix public -b gh-pages
                    git push -f origin gh-pages:gh-pages
                    git branch -D gh-pages